bweight_dta <- read.csv("data_update/data/birthweight_data.csv")
childpov_dta <- read.csv("data_update/data/child_poverty_cpp.csv")
attnment_dta <- read.csv("data_update/data/edu_attainment_cpp_data.csv")
employment_dta <- read.csv("data_update/data/employment_data.csv")
oowb_dta <- read.csv("data_update/data/oowb_data.csv")
p1_bmi_dta <- read.csv("data_update/data/p1_bmi_data.csv")
masterdata <- rbind(bweight_dta, childpov_dta, attnment_dta, employment_dta, oowb_dta, p1_bmi_dta)
write.csv(masterdata, file = "dashboard_data/masterdata.csv", row.names = FALSE)
