bweight_dta <- read.csv("data_update/data/healthy_birthweight_cpp.csv")
childpov_dta <- read.csv("data_update/data/child_poverty_cpp.csv")
attnment_dta <- read.csv("data_update/data/educational_attainment_cpp.csv")
employment_dta <- read.csv("data_update/data/employment_rate_cpp.csv")
oowb_dta <- read.csv("data_update/data/out_of_work_benefits_cpp.csv")
p1_bmi_dta <- read.csv("data_update/data/p1_body_mass_index_cpp.csv")
masterdata <- rbind(bweight_dta, childpov_dta, attnment_dta, employment_dta, oowb_dta, p1_bmi_dta)

currentDate <- format(Sys.Date(), "%d_%m_%y")
write.csv(masterdata, file = paste0("cpop_data/masterdata_",currentDate,".csv"), row.names = FALSE)
